{"stats": {"errors": 1, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 2}, "results": [{"classname": "index_test:HelperTest", "name": "test_int_to_little_endian", "time": 0.0004456043243408203, "type": "failure", "errtype": "builtins.AssertionError", "message": "'01000000' != b'\\x01\\x00\\x00\\x00'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/feulf/bytes-to-int-jsong-pb-denver-070918/test/index_test.py\", line 17, in test_int_to_little_endian\n    self.assertEqual(int_to_little_endian(n, 4), want)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: '01000000' != b'\\x01\\x00\\x00\\x00'\n"}, {"classname": "index_test:HelperTest", "name": "test_little_endian_to_int", "time": 0.0001595020294189453, "type": "error", "errtype": "builtins.TypeError", "message": "Required argument 'byteorder' (pos 2) not found", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/feulf/bytes-to-int-jsong-pb-denver-070918/test/index_test.py\", line 9, in test_little_endian_to_int\n    self.assertEqual(little_endian_to_int(h), want)\n  File \"/home/feulf/bytes-to-int-jsong-pb-denver-070918/index.ipynb\", line 154, in little_endian_to_int\n    \"## Converting from bytes to int and back\\n\",\nTypeError: Required argument 'byteorder' (pos 2) not found\n"}]}